---
title: "Figure 2"
format: html
editor: visual
---

```{r}
sample_data <- read.csv("~/desktop/sample_data.csv")
```

```{r}
rad2ang <- function(rad) {
  return(rad * 180 / pi)
}

mean(circular(sample_data$fast_phase, units = "radians", template = "geographics"), na.rm = TRUE)
mean(circular(sample_data$slow_phase, units = "radians", template = "geographics"), na.rm = TRUE)

sample_data <- sample_data |>
  mutate(phase_ang = (rad2ang(phase)))

count <- max(hist(sample_data$phase_ang, breaks = seq(-180, 180, by = 15))$counts)

sample_phaseplot <- ggplot(sample_data, aes(x = phase_ang, fill = sp_type)) +
  geom_histogram(binwidth = 15, colour = "white", size = 0.4,
                 breaks = seq(-180, 180, by = 15)) +
  labs(x = "Phase (rad)") + 
  theme_bw() +
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.x = element_text(size = 12.8),
    panel.border = element_blank(), 
    panel.grid.major = element_line(color = "lightgrey"),
    panel.grid.minor = element_blank()
  ) +
  coord_polar(start = pi/2, direction = -1) +
  scale_x_continuous(limits = c(-180, 180),
                     breaks = c(-180, seq(-135, 135, by = 45), 180),
                     minor_breaks = seq(-180, 180, by = 15),
    labels = c("","","-π/2","","0","","π/2","","   ±π")) +
  scale_fill_manual(values = c("Fast_SP" = "#2f6db3C8", "Slow_SP" = "#e1997aC8"),
                    labels = c("Fast_SP" = "Fast Spindle", "Slow_SP" = "Slow Spindle")) +
  geom_segment(x = -27.530622, y = 0.08, xend = -27.530622, 
               yend = count*1.14*0.261629461887,
               color = "black",
               size = 1.5) +
  geom_segment(x = 124.331842, y = 0.08, xend = 124.331842, 
               yend = count*1.14*0.22675511109148,
               color = "black",
               size = 1.5) +
  labs(fill = "Spindle Type")
ggsave(file="sample_phaseplot.svg", plot=sample_phaseplot)
```
