---
title: "Wrangle"
subtitle: "Does sleep spindle-slow oscillation coupling contribute to memory consolidation during sleep? A meta-analysis and methodological review"
format: pdf
editor: visual
author: "University of Massachusetts Amherst SomNeuro Lab"
date: "2023-10-05"
date-format: iso
---

```{r}
#| label: setup
#| include: false
library(mosaic)
library(tidyverse)
library(knitr)
library(kableExtra)
library(tidyr)
library(Stat2Data)
library(dplyr)
library(meta)
library(metafor)
library(dmetar)
library(metaDigitise)
library(ICC)
library(wildmeta)
library(future)
library(shinyDigitise)
library(CircStats)
library(Directional)
options(digits = 4)
knitr::opts_chunk$set(fig.pos = "H", out.extra = "",
                      tidy=FALSE, size="small")
```

```{r}
#| warning: false
#| message: false
psycbul <- readxl::read_excel("/Users/thea/Downloads/jopd-5-33-s2.xlsx")
```

```{r}
#| warning: false
#| message: false
psycbul_r <- psycbul |>
  filter(grepl("Pearson's r", Type_of_ES))
```

```{r}
#| warning: false
#| message: false
knitr::kable(favstats(psycbul_r$tau))
```

```{r}
#| warning: false
#| message: false
library(extraDistr)
curve(dht(x, 3, 0.5), 0, 3, col = "blue", ylab = "Density", xlab = "Heterogeneity (\u03c4)", lwd = 2)
curve(dhcauchy(x, 0.5), 0, 3, col = "red", add = TRUE, lwd = 2)
curve(dhcauchy(x, 0.13), 0, 3, col = "orange", add = TRUE, lwd = 2)
curve(dhnorm(x, 0.5), 0, 3, col = "black", add = TRUE, lwd = 2)
abline(v = 1, col = "gray", lty = 2)
legend("topright", legend = c("Half-Student-t (0, 3, 0.5)", "Half-Cauchy (0, 0.5)", "Half-Cauchy (0, 0.13)", "Half-Normal (0, 0.5)"), col = c("blue", "red","orange","black"), lwd = 2, bty = "n")
```

```{r}
library(robvis)
data_rob2 <- read.csv("~/Desktop/ROB2_example.csv")
rob_summary(data_rob2, tool = "ROB2", overall = "TRUE", weighted = "FALSE")
rob_traffic_light(data_rob2, tool = "ROB2", psize = 10)
```

## TMR Memory Retention Rate

$$ MRR(\%) = \frac{\text{Corrected Rate}_\text{post.sleep} }{\text{Corrected Rate}_\text{pre.sleep} } \ \times \ 100 \% \tag{4}$$

where $$ \text{Corrected Rate}(\%) = \frac{\text{Hit} - \text{False Alarm}} {\text{Hit}} \ \times \ 100 \%$$

```{r}
library(tfprobability)
tfd_truncated_cauchy(
  0.13,
  0.5,
  0,
  99,
  name = "TruncatedCauchy"
)
```
